[package]
name = "rust-exp"
version = "0.1.0"
authors = ["Neven Miculinic <neven.miculinic@gmail.com>"]
edition = "2018"

[dependencies]
rand = "0.6.1"
base64 = '0.10.0'
hex = '0.3.2'
serde = "1.0.82"
serde_cbor = "0.9.0"
rv='0.4.1'
hamming = "0.1"
openssl="0.10.16"
pretty-hex="0.1.0"
